name: skillmatch

services:
    php:
        build: .
        container_name: php_con
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        environment:
            APP_ENV: dev
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network

    db:
        image: mysql
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_USER: mysql
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network
        ports:
            -   '3306:3306'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
